### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by YanP10** [jassellmedina09/Campus_Resource_Locator#2]

**Comment by kfilipau** [comment]
As a team create a google form (with edit access to all team members) to ask users for input on your project idea.  These questions will be graded based on their quality and ingenuity. The questions should reflect what you have learned in the lessons on what good user research should include.  Test your survey to make sure it works correctly before publicly releasing it. In the survey:

Provide a brief summary of your product idea
Ask at least seven questions
[How to Write Good (Even Great!) Survey Questions](https://blog.hubspot.com/service/survey-questions)
[Writing good survey questions](https://www.surveymonkey.com/mp/writing-survey-questions/)
AI can help to generate questions for a user research survey of your product.
Ask questions to determine what persona type (if any) the user is in (e.g. ask their age and gender, or whatever else is important in your personas). 
At least one question with paragraph expected responses
Use parameter checking at least 3 times
[Set rules for your form](https://support.google.com/docs/answer/3378864?hl=en)
Have a custom “Confirmation message”
[Change a form’s confirmation message](https://support.google.com/a/users/answer/9308742?hl=en)
If your customers are from a specific demographic, ask questions to determine if the responders are in that demographic (e.g. ask age if that is important).
Ask friends and family to take your survey. Consider posting it on your social media. If you have a specific demographic of customer, try to reach them to take your survey.

Post a link to your survey in the Brightspace Discussions forum for your section (Section 1, 2, 3). You personally must take the surveys of all teams in your section.

You must post your survey ASAP because all responses from your audience are due by the due date for this part of the assignment; your team will analyze responses in the next class meeting
